"""Convert CLAWD MOCHI's logo tables into the Claude HUD boot animation files.

The mochi sketch keeps its logo as two PROGMEM tables:

    LOGO_TRIS[162][6]   filled triangles, every one sharing the centre apex
    LOGO_SEGS[162][4]   the same contour as line segments, drawn progressively

Reading them out of a .ino is a parse-and-verify job, not a transcription job:
162 hand-written rows is exactly the size where a single mistyped digit is
invisible on screen and impossible to find by eye. So this tool parses the
source, prints a checksum, and cross-checks that the two tables describe the
same shape (each triangle's two far vertices must equal one segment).

Outputs, all in one directory:

    meta.json   timing and colours, human-editable
    tris.bin    6 x int16 LE per triangle, streamed to the panel at the end
    segs.bin    4 x int16 LE per segment, streamed during the reveal

The firmware reads tris.bin/segs.bin a few entries at a time, so a 162-entry
logo never sits in RAM as primitives.

With --cpp, the same three blobs are also emitted as PROGMEM arrays in a C
header. The firmware writes them to /boot on a first boot, so a freshly
flashed device plays the animation without waiting for a BLE upload. The .bin
files stay the BLE-upload path, and both come out of one run so they cannot
disagree.

    python tools\\mochi_to_boot.py <mochi.ino> <outdir> [--verify-only]
                                      [--cpp firmware\\claude_hud\\boot_data.h]
"""
from __future__ import annotations

import argparse
import json
import re
import struct
import sys
from pathlib import Path
from string import Template

MOCHI_DEFAULT = Path(r"F:\桌宠代码\clawd-mochi\clawd_mochi\clawd_mochi.ino")

# {a,b,c,...} with optional whitespace, int16 values only.
ROW_RE = re.compile(r"\{([^{}]*)\}")


def parse_rows(body: str) -> list[tuple[int, ...]]:
    rows: list[tuple[int, ...]] = []
    for m in ROW_RE.finditer(body):
        parts = [p.strip() for p in m.group(1).split(",") if p.strip()]
        if len(parts) < 4:
            continue
        try:
            rows.append(tuple(int(p) for p in parts))
        except ValueError:
            # A stray non-numeric row in the table is a source bug, and loading
            # a partial table silently would produce a half-drawn logo.
            raise SystemExit(f"unparseable row: {m.group(0)!r}")
    return rows


def extract_table(text: str, name: str) -> tuple[list[tuple[int, ...]], int]:
    """Pull `static const int16_t NAME[][W] PROGMEM = { ... };` out of the source."""
    start = text.find(name)
    if start < 0:
        raise SystemExit(f"table {name} not found")
    open_brace = text.find("{", text.find("PROGMEM", start))
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                body = text[open_brace + 1:i]
                break
    else:
        raise SystemExit(f"unterminated table {name}")
    return parse_rows(body), len(body.splitlines())


def checksum(rows: list[tuple[int, ...]]) -> int:
    """FNV-1a over the table, so a re-run after an edit shows the diff."""
    h = 0x811C9DC5
    for row in rows:
        for v in row:
            h ^= v & 0xFFFF
            h = (h * 0x01000193) & 0xFFFFFFFF
    return h


# Emitted as a separate header rather than appended to the sketch: the .ino is
# the one file the user opens by hand, and 3.4 KB of hex is not something they
# should scroll past. Template so the C braces need no escaping.
BOOT_DATA_H = Template('''// boot_data.h — GENERATED by tools\\mochi_to_boot.py. Do not edit by hand.
//
// The factory start-up animation, compiled into the sketch. A device that has
// just been flashed has an empty LittleFS, and the animation used to arrive
// only as a ~3.4 KB BLE upload — minutes per device at this link's speed, once
// per device. With this header the sketch itself carries it: claude_hud.ino
// writes these blobs to /boot on the first boot, when the files are absent,
// and from then on boot_anim.h streams them exactly as it does for an
// uploaded animation. An upload still replaces them, so this is a factory
// default, not a lock-in.
//
// Regenerate after editing the logo in the mochi sketch:
//
//   python tools\\mochi_to_boot.py "F:\\桌宠代码\\clawd-mochi\\clawd_mochi\\clawd_mochi.ino" tools\\boot --cpp firmware\\claude_hud\\boot_data.h
//
// Provenance, so a stale header is visible without running anything:
//   source     $source
//   meta.json  $meta_len bytes
//   segs.bin   $segs_len bytes ($segs_n x 8), table checksum $segs_cksum
//   tris.bin   $tris_len bytes ($tris_n x 12), table checksum $tris_cksum
//
// check_firmware.py verifies these bytes still match tools\\boot — two copies
// of the animation are two copies that can drift.

#pragma once
#include <Arduino.h>   // PROGMEM

// PROGMEM, not a plain array: these are read once per device at first boot,
// and a RAM copy of 3.4 KB is 3.4 KB the boot path does not need to spend.
// They must be staged through a RAM buffer on the way out — File::write()
// dereferences its argument as RAM, so passing a PROGMEM pointer directly
// writes from the wrong address.

static const uint8_t BOOT_DEFAULT_META[] PROGMEM = {
$meta
};
#define BOOT_DEFAULT_META_LEN $meta_len

static const uint8_t BOOT_DEFAULT_SEGS[] PROGMEM = {
$segs
};
#define BOOT_DEFAULT_SEGS_LEN $segs_len

static const uint8_t BOOT_DEFAULT_TRIS[] PROGMEM = {
$tris
};
#define BOOT_DEFAULT_TRIS_LEN $tris_len
''')


def c_bytes(data: bytes) -> str:
    return "\n".join(
        "  " + " ".join(f"0x{b:02X}," for b in data[i:i + 16])
        for i in range(0, len(data), 16)
    )


def write_cpp_header(path: Path, source: Path, meta: bytes, segs: bytes,
                    tris: bytes, nsegs: int, ntris: int,
                    segs_ck: int, tris_ck: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(BOOT_DATA_H.substitute(
        source=str(source),
        meta_len=len(meta),
        segs_n=nsegs, segs_len=len(segs),
        tris_n=ntris, tris_len=len(tris),
        segs_cksum=f"{segs_ck:08x}", tris_cksum=f"{tris_ck:08x}",
        meta=c_bytes(meta),
        segs=c_bytes(segs),
        tris=c_bytes(tris),
    ), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source", nargs="?", default=str(MOCHI_DEFAULT))
    ap.add_argument("outdir", nargs="?", default=None)
    ap.add_argument("--verify-only", action="store_true",
                    help="parse and cross-check, write nothing")
    ap.add_argument("--cpp", metavar="PATH",
                    help="also emit a C header with the three blobs as "
                         "PROGMEM arrays, so flashing the sketch alone "
                         "carries the animation")
    args = ap.parse_args()

    src = Path(args.source)
    if not src.exists():
        print(f"source not found: {src}")
        return 2
    text = src.read_text(encoding="utf-8", errors="replace")

    tris, _ = extract_table(text, "LOGO_TRIS")
    segs, _ = extract_table(text, "LOGO_SEGS")

    problems: list[str] = []

    # ── shape checks ────────────────────────────────────────────
    if len(tris) != len(segs):
        problems.append(f"count mismatch: {len(tris)} tris vs {len(segs)} segs")

    # Every triangle's far edge must be one of the segments. The mochi data
    # shares an apex, so this also validates the fan construction.
    seg_set = set()
    for x1, y1, x2, y2 in segs:
        seg_set.add((x1, y1, x2, y2))
        seg_set.add((x2, y2, x1, y1))
    matched = 0
    for t in tris:
        if len(t) != 6:
            problems.append(f"triangle does not have 6 values: {t}")
            continue
        ax, ay = t[0], t[1]
        if (t[2], t[3], t[4], t[5]) in seg_set or \
           (t[4], t[5], t[2], t[3]) in seg_set:
            matched += 1
    if matched != len(tris):
        problems.append(f"only {matched}/{len(tris)} triangles match a segment")

    # Coordinates must fit the 240x240 panel, or the reveal draws off-screen.
    all_vals = [v for row in tris for v in row] + [v for row in segs for v in row]
    lo, hi = min(all_vals), max(all_vals)
    if lo < 0 or hi > 240:
        problems.append(f"coordinates outside 0..240: {lo}..{hi}")

    print(f"source      {src}")
    print(f"triangles   {len(tris)}  checksum {checksum(tris):08x}")
    print(f"segments    {len(segs)}  checksum {checksum(segs):08x}")
    print(f"matched     {matched}/{len(tris)} triangles align with a segment")
    print(f"bbox        x {min(v for row in segs for v in row[0::2])}.."
          f"{max(v for row in segs for v in row[0::2])}   "
          f"y {min(v for row in segs for v in row[1::2])}.."
          f"{max(v for row in segs for v in row[1::2])}")

    if problems:
        print("\nPROBLEMS:")
        for p in problems:
            print(f"  - {p}")
        return 1
    print("\ndata verified: the two tables describe the same logo")

    if args.verify_only:
        return 0

    meta = {
        "schema": 1,
        "duration_ms": 1600,     # one segment per ~10ms: 162 segs ≈ 1.6s
        "hold_ms": 1200,         # logo stays up before the HUD takes over
        "loop": False,
        "bg": "#DA1100",         # the Claude HUD firmware's own background
        "color": "#FFFFFF",
        "segments": len(segs),
        "triangles": len(tris),
    }
    meta_bytes = json.dumps(meta, indent=2, ensure_ascii=False).encode("utf-8")
    segs_bytes = b"".join(struct.pack("<4h", *row) for row in segs)
    tris_bytes = b"".join(struct.pack("<6h", *row) for row in tris)

    if args.outdir:
        out = Path(args.outdir)
        out.mkdir(parents=True, exist_ok=True)

        (out / "meta.json").write_bytes(meta_bytes)
        (out / "segs.bin").write_bytes(segs_bytes)
        (out / "tris.bin").write_bytes(tris_bytes)

        print(f"\nwrote {out}")
        print(f"  meta.json    {len(meta_bytes)} bytes")
        print(f"  segs.bin     {len(segs_bytes)} bytes  ({len(segs)} x 8)")
        print(f"  tris.bin     {len(tris_bytes)} bytes  ({len(tris)} x 12)")
        print(f"  total        {len(segs_bytes) + len(tris_bytes)} bytes of the ~1.5 MB LittleFS")

    if args.cpp:
        cpp = Path(args.cpp)
        write_cpp_header(cpp, src, meta_bytes, segs_bytes, tris_bytes,
                         len(segs), len(tris),
                         checksum(segs), checksum(tris))
        print(f"\nwrote {cpp}")
        print(f"  boot_data.h  {cpp.stat().st_size} bytes "
              f"(compiled into the sketch; first boot writes it to /boot)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
